Login overlay
croma-app/huehive-mobile-app pull request #224
Opened 2024-04-15 04:49 UTC by bhujoshi

2024-04-15 04:52 UTC, bhujoshi commented
Basic UI build for login overlay working on functionality.
![Screenshot 2024-04-15 at 10 20 21 AM](https://github.com/croma-app/huehive-mobile-app/assets/9627563/987cd83f-5494-4c7f-8aa2-0cd982d0929e)
![Screenshot 2024-04-15 at 10 20 10 AM](https://github.com/croma-app/huehive-mobile-app/assets/9627563/9ef3b7d7-62d7-446c-8c6d-998222ff0d13)

2024-04-16 10:18 UTC, kamalkishor1991 requested changes

2024-04-16 10:18 UTC, kamalkishor1991 commented on components/GridActionButton.android.js
> +        style={{ height: 400 }}
We should make it percentage of screen height and also move it to styles

2024-04-16 10:18 UTC, kamalkishor1991 commented on components/Login.js
> +    // setError(error.message);
We should show errors like this to users also and send the error to server for us to debug 
https://github.com/croma-app/huehive-mobile-app/blob/7012a4971cf54586edf2ff2b33e05638081e0309/libs/Helpers.js#L20

2024-04-16 10:18 UTC, kamalkishor1991 commented on screens/ChatSessionScreen.js
> +export default loginHoc(ChatSessionScreen);
nice.

2024-04-21 12:54 UTC, kamalkishor1991 requested changes

2024-04-21 12:54 UTC, kamalkishor1991 commented on components/LoginWrapper.js
> +const LoginWrapper = function ({ children }) {
AppAuthProvider is a better name.

2024-04-21 12:54 UTC, kamalkishor1991 commented on components/LoginWrapper.js
> +const LoginOverlay = function () {
AuthOverlay

2024-04-21 12:54 UTC, kamalkishor1991 commented on components/LoginWrapper.js
> +    height: Dimensions.get('window').height,
We should try to avoid depending on Dimensions in this case.

2024-04-21 12:54 UTC, kamalkishor1991 commented on hooks/useLoginOverlay.js
> +const useLoginOverlay = create((set) => ({
we can call it useAuth I think?

2024-04-21 12:54 UTC, kamalkishor1991 commented on hooks/useUserData.js
> +      console.log('Error: Failed to load userData');
do we need catch here?

2024-04-22 04:27 UTC, bhujoshi commented on components/ForgetPassword.js
> +import React, { useState } from 'react';
Removed

2024-04-22 04:34 UTC, bhujoshi commented on components/LoginWrapper.js
> +const LoginWrapper = function ({ children }) {
Changed

2024-04-22 04:34 UTC, bhujoshi commented on components/LoginWrapper.js
> +const LoginOverlay = function () {
Changed

2024-04-22 04:43 UTC, bhujoshi commented on hooks/useLoginOverlay.js
> +const useLoginOverlay = create((set) => ({
Done

2024-04-22 04:43 UTC, bhujoshi commented on hooks/useUserData.js
> +      console.log('Error: Failed to load userData');
removed

2024-04-22 14:04 UTC, merged